---
branches:
  - main
  - next
tagFormat: v${version}
plugins:
  - "@semantic-release/commit-analyzer"
  # - "@semantic-release/git"
  - "@semantic-release/release-notes-generator"
  # - "@semantic-release/changelog"
debug: true
