---
template:
  type: file
  path: bucket.yaml.j2

hooks:
  before_delete:
    # See https://towardsthecloud.com/aws-cli-empty-s3-bucket for emptying versions enabled S3 bucket
    - !cmd |
      aws_account_id=$(aws sts get-caller-identity --query "Account" --output text)
      bucket_name="${aws_account_id}-{{template_bucket_suffix}}"
      aws s3 rm "s3://${bucket_name}" --recursive

sceptre_user_data:
  project_code: "{{ stack_group_config.project_code }}"
  source_repo_url: "{{source_repo_url}}"
  buckets:
    - name: SceptreArtifact
      deletion_policy: Delete
      update_replace_policy: Delete
      bucket_name: "!Sub ${AWS::AccountId}-{{template_bucket_suffix}}"
      access_control: Private
      bucket_encryption:
        server_side_encryption_configuration:
          - bucket_key_enabled: true
            server_side_encryption_by_default:
              sse_algorithm: aws:kms
      public_access_block_configuration:
        block_public_acls: true
        block_public_policy: true
        ignore_public_acls: true
        restrict_public_buckets: true
      lifecycle_configuration:
        rules:
          - status: Enabled
            expiration_in_days: 365
      bucket_policy:
        policy_document: |
          Version: "2012-10-17"
          Id: BucketPolicy
          Statement:
            - Sid: AllowSSLRequestsOnly
              Action: s3:*
              Effect: Deny
              Resource:
                - !GetAtt SceptreArtifact.Arn
                - !Join ['/', [!GetAtt SceptreArtifact.Arn, '*']]
              Condition:
                Bool:
                  aws:SecureTransport: false
              Principal: "*"
      tags:
        Project: "{{project_code}}"
        SourceRepoUrl: "{{source_repo_url}}"
