---
template:
  type: http
  url: https://s3.amazonaws.com/solutions-reference/instance-scheduler-on-aws/{{solution_version}}/instance-scheduler-on-aws-remote.template

parameters:
  # Version v3.0.5
  # PG: Account Structure
  InstanceSchedulerAccount: "{{account_id_hub}}"
  UsingAWSOrganizations: "No"
  Namespace: "{{solution_namespace}}"
  # # PG: Service-specific
  # KmsKeyArns:

stack_tags:
  SourceRepoUrl: "{{source_repo_url}}"
